/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Color;

/**
 *
 * @author user
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
    }
    
    Color light = new Color(153,153,153);
    Color dark = new Color(27,27,27); 
    Color bodyColor = new Color(51,204,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        navBar = new javax.swing.JPanel();
        UserGroup = new javax.swing.JPanel();
        UserIcon = new javax.swing.JPanel();
        userIconImg = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        dashPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(27, 27, 27));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBar.setBackground(new java.awt.Color(27, 27, 27));
        navBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        navBar.setForeground(new java.awt.Color(255, 255, 255));
        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserGroup.setBackground(new java.awt.Color(27, 27, 27));
        UserGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserGroupMouseClicked(evt);
            }
        });
        UserGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserIcon.setBackground(new java.awt.Color(27, 27, 27));
        UserIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIconImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/userIcon.png"))); // NOI18N
        userIconImg.setText("jLabel3");
        UserIcon.add(userIconImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        UserGroup.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 13, 140, 110));

        UserLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("USERS");
        UserGroup.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        navBar.add(UserGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 160));

        jDesktopPane1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 510));

        header.setBackground(new java.awt.Color(27, 27, 27));
        header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashPane.setBackground(new java.awt.Color(27, 27, 27));
        dashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(27, 27, 27));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        dashPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        header.add(dashPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 33));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        dashPane.setBackground(light);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        dashPane.setBackground(dark);
    }//GEN-LAST:event_jLabel1MouseExited

    private void UserGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserGroupMouseClicked
        userForm usf = new userForm();
        usf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserGroupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserGroup;
    private javax.swing.JPanel UserIcon;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel dashPane;
    private javax.swing.JPanel header;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel navBar;
    private javax.swing.JLabel userIconImg;
    // End of variables declaration//GEN-END:variables
}
