/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import config.dbConnector;
import java.sql.ResultSet;
import dashBoard.*;
import java.awt.Color;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class userForm extends javax.swing.JFrame {

    /**
     * Creates new form dashBoard
     */
    public userForm() {
        initComponents();
        displayData();
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT client_id, client_Fname,	client_Lname, client_Email FROM client_tbl");
            userTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }
    
    Color light = new Color(153,153,153);
    Color dark = new Color(27,27,27); 
    Color bodyColor = new Color(51,204,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        navBar = new javax.swing.JPanel();
        dashPane = new javax.swing.JPanel();
        userPane = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        BackLabel = new javax.swing.JLabel();
        UserFormLabel = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        jLabel2.setBackground(new java.awt.Color(27, 27, 27));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER PAGE");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        navBar.setBackground(new java.awt.Color(27, 27, 27));
        navBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashPane.setBackground(new java.awt.Color(27, 27, 27));
        dashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        navBar.add(dashPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 225, -1, 33));

        userPane.setBackground(new java.awt.Color(27, 27, 27));
        userPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        navBar.add(userPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 296, 106, 33));

        jPanel1.add(navBar);
        navBar.setBounds(0, 70, 130, 510);

        header.setBackground(new java.awt.Color(27, 27, 27));
        header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackLabel.setBackground(new java.awt.Color(27, 27, 27));
        BackLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        BackLabel.setForeground(new java.awt.Color(255, 255, 255));
        BackLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BackLabel.setText("BACK");
        BackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackLabelMouseExited(evt);
            }
        });
        header.add(BackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 140, 50));

        UserFormLabel.setBackground(new java.awt.Color(27, 27, 27));
        UserFormLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UserFormLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserFormLabel.setText("USERS FORM");
        UserFormLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserFormLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserFormLabelMouseExited(evt);
            }
        });
        header.add(UserFormLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 50));

        jPanel1.add(header);
        header.setBounds(0, 0, 910, 70);

        jDesktopPane1.setBackground(new java.awt.Color(27, 27, 27));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(130, 70, 780, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseEntered
        dashPane.setBackground(light);
    }//GEN-LAST:event_BackLabelMouseEntered

    private void BackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseExited
        dashPane.setBackground(dark);
    }//GEN-LAST:event_BackLabelMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void UserFormLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserFormLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFormLabelMouseEntered

    private void UserFormLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserFormLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFormLabelMouseExited

    private void BackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLabelMouseClicked
        adminDashboard ds = new adminDashboard();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLabel;
    private javax.swing.JLabel UserFormLabel;
    private javax.swing.JPanel dashPane;
    private javax.swing.JPanel header;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel userPane;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
